name: personel_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^7.1.2
  cupertino_icons: ^1.0.4
  google_fonts: ^4.0.4
  image_picker: ^0.8.7+5
  provider: ^6.0.1
  equatable: ^2.0.5
  http: ^0.13.0
  async: ^2.11.0
  intl: ^0.18.1
  image_cropper: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
