import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

ThemeData lightThemeData(BuildContext context) {
  return FlexThemeData.light(
    colors: const FlexSchemeColor(
      primary: Color(0xff1145a4),
      primaryContainer: Color(0xff9fb4da),
      secondary: Color(0xffb61d1d),
      secondaryContainer: Color(0xffe1a4a4),
      tertiary: Color(0xff376bca),
      tertiaryContainer: Color(0xffcfdbf2),
      appBarColor: Color(0xffcfdbf2),
      error: Color(0xffb00020),
    ),
    surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
    blendLevel: 5,
    appBarOpacity: 0.95,
    swapColors: true,
    subThemesData: const FlexSubThemesData(
      useFlutterDefaults: true,
      blendOnLevel: 20,
      blendOnColors: false,
      blendTextTheme: false,
      defaultRadius: 8.0,
      inputDecoratorIsFilled: false,
      inputDecoratorUnfocusedBorderIsColored: false,
      bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.onPrimary,
      bottomNavigationBarUnselectedLabelSchemeColor: SchemeColor.onPrimary,
      bottomNavigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
      bottomNavigationBarUnselectedIconSchemeColor: SchemeColor.onPrimary,
      bottomNavigationBarBackgroundSchemeColor: SchemeColor.primary,
      bottomNavigationBarElevation: 4.0,
      bottomNavigationBarShowUnselectedLabels: false,
      navigationBarSelectedLabelSchemeColor: SchemeColor.onPrimary,
      navigationBarUnselectedLabelSchemeColor: SchemeColor.onPrimary,
      navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
      navigationBarUnselectedIconSchemeColor: SchemeColor.onPrimary,
      navigationBarIndicatorSchemeColor: SchemeColor.surface,
      navigationBarIndicatorOpacity: 0.15,
      navigationBarBackgroundSchemeColor: SchemeColor.primary,
      navigationBarHeight: 60.0,
      navigationBarLabelBehavior: NavigationDestinationLabelBehavior.onlyShowSelected,
      navigationRailIndicatorSchemeColor: SchemeColor.primary,
      navigationRailLabelType: NavigationRailLabelType.selected,
    ),
    keyColors: const FlexKeyColors(
      useSecondary: true,
      useTertiary: true,
      keepSecondary: true,
      keepTertiary: true,
      keepSecondaryContainer: true,
      keepTertiaryContainer: true,
    ),
    tones: FlexTones.vivid(Brightness.light),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
  );
}

ThemeData darkThemeData(BuildContext context) {
  return FlexThemeData.dark(
    colors: const FlexSchemeColor(
      primary: Color(0xff1145a4),
      primaryContainer: Color(0xff9fb4da),
      secondary: Color(0xffb61d1d),
      secondaryContainer: Color(0xffe1a4a4),
      tertiary: Color(0xff376bca),
      tertiaryContainer: Color(0xffcfdbf2),
      appBarColor: Color(0xffcfdbf2),
      error: Color(0xffb00020),
    ),
    surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
    blendLevel: 10,
    appBarStyle: FlexAppBarStyle.primary,
    appBarOpacity: 0.90,
    subThemesData: const FlexSubThemesData(
      useFlutterDefaults: true,
      blendOnLevel: 30,
      defaultRadius: 8.0,
      inputDecoratorIsFilled: false,
      inputDecoratorUnfocusedBorderIsColored: false,
      tabBarItemSchemeColor: SchemeColor.onPrimary,
      tabBarIndicatorSchemeColor: SchemeColor.onPrimary,
      bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.onPrimary,
      bottomNavigationBarUnselectedLabelSchemeColor: SchemeColor.onPrimary,
      bottomNavigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
      bottomNavigationBarUnselectedIconSchemeColor: SchemeColor.onPrimary,
      bottomNavigationBarBackgroundSchemeColor: SchemeColor.primary,
      bottomNavigationBarElevation: 4.0,
      bottomNavigationBarShowUnselectedLabels: false,
      navigationBarSelectedLabelSchemeColor: SchemeColor.onPrimary,
      navigationBarUnselectedLabelSchemeColor: SchemeColor.onPrimary,
      navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
      navigationBarUnselectedIconSchemeColor: SchemeColor.onPrimary,
      navigationBarIndicatorSchemeColor: SchemeColor.surface,
      navigationBarIndicatorOpacity: 0.15,
      navigationBarBackgroundSchemeColor: SchemeColor.primary,
      navigationBarHeight: 60.0,
      navigationBarLabelBehavior: NavigationDestinationLabelBehavior.onlyShowSelected,
      navigationRailIndicatorSchemeColor: SchemeColor.primary,
      navigationRailLabelType: NavigationRailLabelType.selected,
    ),
    keyColors: const FlexKeyColors(
      useSecondary: true,
      useTertiary: true,
      keepSecondary: true,
      keepPrimaryContainer: true,
      keepSecondaryContainer: true,
    ),
    tones: FlexTones.vivid(Brightness.dark),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
  );
}
